<a href="https://colab.research.google.com/github/dhanusya-ds/Python_Basics/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
num = [10,20,30]
for i in num:
  print(i*2)

20
40
60


1D Array

In [7]:
import numpy as np
num = np.array([10,20,30])
num

array([10, 20, 30])

In [8]:
print(num)
print(num*2)

[10 20 30]
[20 40 60]


In [9]:
print(type(num))

<class 'numpy.ndarray'>


2D array

In [10]:
num2 = np.array([[1,2],[3,4]])
print(num2)

[[1 2]
 [3 4]]


3D array

In [11]:
num3 = np.array([
    [
        [1,2],[3,4]
        ],
    [
     [5,6],[7,8]
    ]
    ])
print(num3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


array dimension

In [12]:
arr = np.array([1,2])
print(arr.ndim)

1


In [13]:
arr2 = np.array([[1,2],[3,4]])
print(arr2.ndim)

2


In [14]:
arr3 = np.array([
    [
        [1,2],[3,4]
    ],
    [
        [5,6],[7,8]
    ]
])
print(arr3.ndim)

3


Shape

In [21]:
arr1 = np.array([[1,2,3],[5,6,7]])
print(arr1.shape)
arr2 = np.array([[5,6],[5,3],[8,4]])
print(arr2.shape)

(2, 3)
(3, 2)


Size

In [24]:
print(arr2.size)
print(num3.size)

6
8


data Type

In [25]:
print(arr1.dtype)

int64


In [26]:
n1 = np.array([[1.34,5.35]])
print(n1.dtype)

float64


Special Arrays

In [30]:
#zeros
n0 = np.zeros((3,3))
print(n0)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [31]:
#ones
n1= np.ones((3,3))
print(n1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [37]:
#empty
emp = np.empty((2,2))
print(emp)

[[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]]


In [40]:
#identity matrix
idm = np.identity(3)
print(idm)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Range

In [41]:
#arange
arr = np.arange(1,6)
print(arr)

[1 2 3 4 5]


In [43]:
arr = np.arange(0,11,2)
print(arr)

[ 0  2  4  6  8 10]


linspace , equally sapced numbers

In [48]:
arr = np.linspace(1,6,5)
print(arr)

[1.   2.25 3.5  4.75 6.  ]


reshape ( convert to matrix )

In [53]:
arr = np.arange(1,13)
print(arr)


[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [56]:
print(arr.reshape(4,3))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Flatten (converts matrix into single array

In [57]:
arr = np.array([
    [1,2],
     [4,6]
])
print(arr.flatten())

[1 2 4 6]


Indexing

In [58]:
arr = np.array([12,34,65,23,75])
print(arr[0])

12


In [60]:
#slicing
print(arr[2:5])

[65 23 75]


In [61]:
print(arr[-1])

75


In [63]:
#2d indexing

arr = np.array([
    [3,6],[6,8],[2,6]
])
print(arr[1][1])

8


In [64]:
print(arr[1,1])

8


Array operation


In [66]:
a = np.array([2,8,1])
b = np.array([3,5,7])
print(a+b)

[ 5 13  8]


In [67]:
print(a-b)

[-1  3 -6]


In [68]:
print(a*b)

[ 6 40  7]


In [69]:
print(a/b)

[0.66666667 1.6        0.14285714]


Math Function

In [70]:
arr = np.array([4,3,6,2])
print(np.sqrt(arr))

[2.         1.73205081 2.44948974 1.41421356]


In [71]:
print(np.power(arr,2))

[16  9 36  4]


In [72]:
print(np.square(arr))

[16  9 36  4]


aggregate functions

In [73]:
arr = np.array([2,3,5,6])
print(np.sum(arr))

16


In [74]:
print(np.mean(arr))

4.0


In [75]:
print(np.max(arr))

6


In [76]:
print(np.min(arr))

2


In [117]:
print(np.argmax(arr))

4


In [118]:
print(np.argmin(arr))

0


In [119]:
print(np.unique(arr))

[10 20 30 40 50]


Random numbers

In [80]:
arr = np.random.rand(1,2)
print(arr)


[[0.2095751  0.33392069]]


In [87]:
arr = np.random.randint(1,50,8)
print(arr)

[12 37  1 48  3 47  6 22]


Copy vs View

In [104]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]


In [105]:
a = np.array([1,2,3])
b= a.view()
b[1]= 100
print(a)

[  1 100   3]


In [107]:
m = np.array([5,6,7])
n = m.copy()
v = m.view()
print(m)
print(n)
print(v)

[5 6 7]
[5 6 7]
[5 6 7]


Sorting

In [113]:
arr = np.array([5,2,6,8,35,1])
b = np.sort(arr)
print(b)



[ 1  2  5  6  8 35]


In [114]:
#find 2nd max num ijn array
arr = np.array([5,2,6,8,35,1])
b = np.sort(arr)
c = np.max(b[-2])
print(b)
print(c)

[ 1  2  5  6  8 35]
8


Boolean filtering

In [116]:
arr = np.array([10,20,30,40,50])

print(arr>25)
print(arr[arr>25])

[False False  True  True  True]
[30 40 50]


In [124]:
#problem
arr = np.array([12,45,7,89,23])
print(arr)
print(np.max(arr)) #max
print(np.min(arr)) #min
print(np.average(arr)) #avg

[12 45  7 89 23]
89
7
35.2


In [131]:
#find max element without using np.max()
arr = np.array([8, 3, 15, 2, 20, 10])
a=np.sort(arr)
b = a[-1]
print(a)
print(b)

m = np.sort(arr)[-1]
print(m)


[ 2  3  8 10 15 20]
20
20


In [133]:
import numpy as np

arr = np.array([12, 45, 7, 89, 23])
max_num = arr[0]
for i in arr:
    if i > max_num:
        max_num = i

print(max_num)

89
